import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import {FormsModule, ReactiveFormsModule} from '@angular/forms';

import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { AppComponent } from '@src/app/app.component';
import { MDBBootstrapModule } from 'angular-bootstrap-md';
import { LoginComponent } from '@src/app/login/login.component';
import { SignupComponent } from '@src/app/signup/signup.component';
import { RouterModule, Routes } from '@angular/router';
import { DashboardComponent} from '@src/app/dashboard/dashboard.component';
import { HeaderComponent } from '@src/app/header/header.component';
import { PostComponent } from '@src/app/post/post.component'
import { HttpClientModule } from '@angular/common/http';
import { MypostComponent } from '@src/app/mypost/mypost.component'; 
import { EditComponent } from '@src/app/edit/edit.component';
import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';
import { routes } from '@src/app/app-routing.module';

const appRoutes: Routes = [
  {
    path:'',
    component:LoginComponent
  },
  {
    path:'signup',
    component:SignupComponent
  },
  {
    path:'dashboard',
    component:DashboardComponent
  },
  {
    path:'post',
    component:PostComponent
  },
  {
    path:'mypost',
    component:EditComponent
  }

]
@NgModule({
  declarations: [
    AppComponent,
    LoginComponent,
    SignupComponent,
    DashboardComponent,
    HeaderComponent,
    PostComponent,
    MypostComponent,
    EditComponent,
    AutoGeneratedComponent
  ],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    MDBBootstrapModule.forRoot(),
    FormsModule,
    RouterModule.forRoot(routes),
    RouterModule.forRoot(appRoutes),
    HttpClientModule,


  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
